### ISSUE TITLE
Autocomplete layer is not updating after deleting last letter of query with backspace key

### ISSUE THREAD

**Issue by happyhj** [skplanet/sweetsearch#1]
## Description
On [demo page](http://nigayo.github.io/page/sweetsearch/demo/searchAmazon.html), autocomplete layer is not updating after deleting last letter of query with backspace key.

## Reproduction
1. Go to demo page http://nigayo.github.io/page/sweetsearch/demo/searchAmazon.html
2. Type 'a' at input area.
3. You can see autocomplete items.
<img width="376" alt="screen shot 2016-04-07 at 8 21 57 pm" src="https://cloud.githubusercontent.com/assets/3903575/14349512/9487f2ea-fcfe-11e5-92cd-6c6dc0c35d37.png">

4. Remove query 'a' by pressing backspace key.
5. Autocomplete items for 'a' is still there.

<img width="375" alt="screen shot 2016-04-07 at 8 22 06 pm" src="https://cloud.githubusercontent.com/assets/3903575/14349583/fe1303b2-fcfe-11e5-8043-55a1b4749a75.png">

## Expected
After removing last letter of query, autocomplete layer should disappear.
<img width="377" alt="screen shot 2016-04-07 at 8 28 04 pm" src="https://cloud.githubusercontent.com/assets/3903575/14349659/66839d94-fcff-11e5-9079-80bfe50a61b9.png">

**Comment by nigayo** [comment]
close issue.
